---
- name: Install Nginx and Node.js on EC2
  hosts: all
  become: yes

  tasks:
    - name: Update YUM cache
      command: yum makecache

    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Install Node.js
      yum:
        name: nodejs
        state: present

    - name: Install npm
      yum:
        name: npm
        state: present

